config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
]

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.NewsPageView.as_view(), name="news"),
    path("news/<int:pk>/", views.NewsPageDetailView.as_view(), name="news_detail"),
    path("courses/", views.CoursesListView.as_view(), name="courses"),
    path(
        "courses/<int:pk>/",
        views.CoursesDetailView.as_view(),
        name="courses_detail",
    ),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("login/", views.LoginPageView.as_view(), name="login"),
]

mainapp/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class CoursesManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

mainapp/views.py
from datetime import datetime

from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs):
        # Get all previous data
        context = super().get_context_data(**kwargs)
        # Create your own data
        context["news_title"] = "Громкий новостной заголовок"
        context["news_preview"] = "Предварительное описание, которое заинтересует каждого"
        context["range"] = range(5)
        context["datetime_obj"] = datetime.now()
        return context


class NewsWithPaginatorView(NewsPageView):
    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context["page_num"] = page
        return context


class CoursesPageView(TemplateView):
    template_name = "mainapp/courses_list.html"


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"


class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LoginPageView(TemplateView):
    template_name = "mainapp/login.html"

mainapp/templates/mainapp/contacts.html
{% extends 'base.html' %}
{% load email_to_link %}

{% block content %}

  <p>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Наши контакты</h1>
        <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.
        </p>
      </div>
    </div>
  </p>
  <p>
    <div class="row justify-content-around mt-n2">

      <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
          <div class="card-body">
            <div style="position:relative;overflow:hidden;"><a
              href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:0px;">Петропавловская
              крепость</a><a
                href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:14px;">Достопримечательность
                в
                Санкт‑Петербурге</a><a
                  href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
                  style="color:#eee;font-size:12px;position:absolute;top:28px;">Музей
                  в
                  Санкт‑Петербурге</a><iframe
                    src="https://yandex.ru/map-widget/v1/-/CCUAZHcrhA" width="100%"
                    height="300" frameborder="0" allowfullscreen="true"
                    style="position:relative; border-radius: 4px;"></iframe>
            </div>
            <h5 class="card-title">Санкт‑Петербург</h5>
            <p class="card-text">
              <ul class="list-unstyled">
                <li>Телефон</li>
                <li><strong>+7-999-11-11111</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Email</li>
                <li><strong>{{ 'geeklab@spb.ru'|email_to_link }}</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Адрес</li>
                <li><strong>территория Петропавловская крепость, 3Ж</strong>
                </li>
              </ul>
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
          <div class="card-body">
            <div style="position:relative;overflow:hidden;"><a
              href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:0px;">Казанский
              Кремль</a><a
                href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей
                в Казани</a><a
                  href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
                  style="color:#eee;font-size:12px;position:absolute;top:28px;">Достопримечательность
                  в
                  Казани</a><iframe src="https://yandex.ru/map-widget/v1/-/CCUAZHX3xB"
                    width="100%" height="300" frameborder="0" allowfullscreen="true"
                    style="position:relative; border-radius: 4px;"></iframe>
            </div>
            <h5 class="card-title">Казань</h5>
            <p class="card-text">
              <ul class="list-unstyled">
                <li>Телефон</li>
                <li><strong>+7-999-22-22222</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Email</li>
                <li><strong>{{ 'geeklab@kz.ru'|email_to_link }}</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Адрес</li>
                <li><strong>территория Кремль, 11, Казань, Республика
                  Татарстан, Россия</strong></li>
              </ul>
            </p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
          <div class="card-body">
            <div style="position:relative;overflow:hidden;"><a
              href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:0px;">Собор
              Покрова Пресвятой
              Богородицы на Рву</a><a
                href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей
                в Москве</a><iframe
                  src="https://yandex.ru/map-widget/v1/-/CCUAZHh9kD" width="100%"
                  height="300" frameborder="0" allowfullscreen="true"
                  style="position:relative; border-radius: 4px;"></iframe>
            </div>
            <h5 class="card-title">Москва</h5>
            <p class="card-text">
              <ul class="list-unstyled">
                <li>Телефон</li>
                <li><strong>+7-999-33-33333</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Email</li>
                <li><strong>{{ 'geeklab@msk.ru'|email_to_link }}</strong></li>
              </ul>
              <ul class="list-unstyled">
                <li>Адрес</li>
                <li><strong>Красная площадь, 7, Москва, Россия</strong></li>
              </ul>
            </p>
          </div>
        </div>
      </div>

    </div>
  </p>

{% endblock content %}

mainapp/templates/mainapp/courses_detail.html
{% extends 'base.html' %}
{% load static markdownify %}

{% block title %}
{{ course_object.name }}
{% endblock title %}

{% block content %}
<h1 class="mt-2">
    {{ course_object.name }}
</h1>
<div class="row justify-content-center">
    <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
        <div class="row h-100">
            <div class="col-12">
                {% if course_object.description_as_markdown %}
                {{ course_object.description|markdownify }}
                {% else %}
                {{ course_object.description }}
                {% endif %}
            </div>
            <div class="col-12 align-self-end">
                <p>
                    <small>Преподаватели</small><br>
                    {% for item in teachers %}
                    {{ item.name_second }} {{ item.name_first }}{% if forloop.last %}{% else %},{% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
        <div class="row h-100">
            <div class="col-12 align-self-start">
                <img class="w-100" src="{% static course_object.cover %}">
            </div>
            <div class="col-12 align-self-end d-none d-md-block">
                <p class="text-center mt-2">
                    <small class="text-uppercase">цена</small><br>
                    <span style="font-size: 30pt;">
                        {{ course_object.cost}}
                    </span><br>
                    <a href="#" class="btn btn-outline-primary btn-block" role="button">Купить</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-12 d-md-none order-3 order-sm-3">
        <p class="text-center">
            <small class="text-uppercase">цена</small><br>
            <span style="font-size: 30pt;">
                {{ course_object.cost}}
            </span><br>
            <a href="#" class="btn btn-outline-primary btn-block" role="button">Купить</a>
        </p>
    </div>
</div>
<div class="accordion" id="accordionLessons">

    {% for item in lessons %}
    <div class="card">
        <div class="card-header" id="headLessonPk{{ item.pk }}">
            <h2 class="mb-0">
                <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                    data-target="#collapse{{ item.pk }}" aria-expanded="true" aria-controls="collapse{{ item.pk }}">
                    {{ item.course.name }} - {{ item.title }}
                </button>
            </h2>
        </div>

        <div id="collapse{{ item.pk }}" class="collapse" aria-labelledby="headLessonPk{{ item.pk }}"
            data-parent="#accordionLessons">
            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-12 text-center">
                        <img src="{% static 'img/no_image.svg' %}" width="250px">
                    </div>
                    <div class="col-12">
                        {% if item.description_as_markdown %}
                        {{ item.description|markdownify }}
                        {% else %}
                        {{ item.description }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

mainapp/templates/mainapp/courses_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="row justify-content-center mt-3">


    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course001.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Web Python</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course002.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Web Golang</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course003.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Web JavaScript</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course004.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Web Java</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course005.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Web PHP</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course006.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">Python AI</h5>
        </div>
      </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
      <a href="#">
        <img src="{% static 'img/course007.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-center">DevOps</h5>
        </div>
      </a>
    </div>


  </div>
  <div class="row justify-content-center align-items-center mt-3 mb-n3">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav>
  </div>

{% endblock content %}

mainapp/templates/mainapp/login.html
{% load static %}

<!doctype html>
<html lang="ru">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
  </head>

  <body>





    <div class="row justify-content-around align-items-center"
      style="height: 100vh; margin: 0px">
      <div class="text-center">
        <p>
          <a href="{% url 'mainapp:main_page' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
        </p>
        <h2>Вход пользователя</h2>
        <form>
          <p>
            <input id="id_username" class="form-control" type="text"
              name="username" placeholder="Имя пользователя"
              required="" autofocus="">
          </p>
          <p>
            <input id="id_password" class="form-control" type="password"
              name="password" placeholder="Пароль" required="">
          </p>
          <p>
            <button type="submit"
              class="btn btn-primary btn-block">Войти</button>
          </p>
        </form>
        <p class="text-right">
          <a href=""><small>Забыли пароль?</small></a>
        </p>
        <h4>Вход через социальные сети</h4>
        <p>
          <div class="btn-group btn-block" role="group">
            <a class="btn btn-primary" href="#" role="button"><i
              class="fab fa-vk"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i
              class="fab fa-github"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i
              class="fab fa-facebook"></i></a>
          </div>
        </p>
      </div>
    </div>








    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>



  </body>

</html>

mainapp/templates/mainapp/news.html
{% extends 'base.html' %}

{% block title %}
Новости
{% endblock title %}

{% block content %}

{% if page_num %}
<div class="card my-2">
  <div class="card-body">
    <p class="card-text">Текущая страница: {{ page_num }}</p>
  </div>
</div>
{% endif %}

<div class="row">

  <div class="col-lg-8">

    {% for item in news_qs %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ item.created|date:"Y-m-d h-i-s" }}
        </h6>
        <p class="card-text">{{ item.preambule }}</p>
        <a href="{% url 'mainapp:news_detail' pk=item.pk %}" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}

  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      {# <li class="page-item"><a class="page-link" href="#">3</a></li> #}
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endblock content %}

mainapp/templates/mainapp/news_detail.html
{% extends 'base.html' %}

{% block title %}
{{ news_object.title|default:"Новости" }}
{% endblock title %}

{% block content %}
<div class="row justify-content-center pt-3">
    <div class="col-md-12 col-lg-8">
        <div class="card shadow">
            <div class="card-body">
                <h5 class="card-title">{{ news_object.title }}</h5>
                <p class="card-text">
                    {{ news_object.body }}
                </p>
                <a href="{% url 'mainapp:news' %}"
                    class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

  <!-- FontAwesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

  <title>
    {% block title %}
    Welcome to Braniac!
    {% endblock title %}
  </title>
</head>

<body>

  {% include 'includes/main_menu.html' %}

  <div class="container-md">

    {% block content %}

    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur
    optio est esse? Veritatis laborum expedita
    quibusdam numquam! Expedita amet nisi dolor similique autem, mollitia
    ipsa et, natus vel explicabo
    reprehenderit?

    {% endblock content %}

  </div>

  <!-- Footer -->

  <div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Braniac</strong>
        </p>
        <p>
        <ul class="list-unstyled">
          <li><a href="{% url 'mainapp:main_page' %}">Домашняя</a></li>
          <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
          <li><a href="{% url 'mainapp:login' %}">Войти</a></li>
        </ul>
        </p>
      </div>
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Полезное</strong>
        </p>
        <p>
        <ul class="list-unstyled">
          <li><a href="#">Положения &amp; Условия</a></li>
          <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
          <li><a href="#">Документация по API</a></li>
          <li><a href="{% url 'mainapp:doc_site' %}">Документация по сайту</a>
          </li>
        </ul>
        </p>
      </div>
      <div class="col-sm-6 col-md-3 text-center">
        <p>
          <strong>Мы в социальных сетях</strong>
        </p>
        <p>
        <div class="row justify-content-around">
          <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
          <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
        </div>
        </p>
        <p>
          <strong>Наше приложение</strong>
        </p>
        <p>
        <div class="row justify-content-around">
          <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a>
          </div>
          <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
          <div><a href="#"><i class="fab fa-windows fa-2x"></i></a>
          </div>
        </div>
        </p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div>
        <p><small>&copy; GeekBrains 2021</small></p>
      </div>
    </div>
  </div>

  <!-- /Footer -->




  <!-- JavaScript section -->
  <!-- Bootstrap -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- ChartJs -->
  <script src="{% static 'js/Chart.min.js' %}"></script>

  <!-- FontAwesome -->
  <script src="{% static 'js/fontawesome.all.min.js' %}"></script>



</body>

</html>

templates/includes/main_menu.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
      <img src="{% static 'img/logo.png' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
        </li>
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="ddProfile"
            role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Профиль
          </a>
          <div class="dropdown-menu" aria-labelledby="ddProfile">
            <a class="dropdown-item" href="#">Редактировать
              профиль</a>
            <a class="dropdown-item" href="#">Мои курсы</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Модерация</a>
            <a class="dropdown-item" href="#">Административный
              раздел</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Выход</a>
          </div>
        </li>
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
        </li>
      </ul>
      <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a
        href="#">🇬🇧</a></span>
    </div>
  </div>
</nav>